### ISSUE TITLE
H% 너비가 좁은 셀이 아닌 넓은 셀로 인식되는 문제

### ISSUE THREAD

**Issue by Ariette** [HAERUHAERU/mopimopi#1]
안녕하세요?
항상 좋은 스킨 감사합니다. 인벤 아이디가 없는 관계로 부득이하게 이쪽으로 피드백 드리게 되었습니다.
제목대로 H%의 너비가 D%, Death, Swing 등과 같은 좁은 셀(narrowCell1)이 아니라 Damage 등과 같은 넓은 셀(wideCell1)로 적용되는 버그가 있습니다.
작동에는 큰 영향 없는 오류입니다만, 미관상(?) 좋지 않은 관계로 수정 부탁드립니다.

별개로 job 칸을 narrowCell1에서 분리해 고정 크기(예컨데 셀 높이와 같은 2rem)로 설정하거나 적어도 D% 등과 다른 너비를 가질 수 있도록 해주실 수 있을까요?
아이콘은 정사각형인데 D%, Swing 등에 좁은셀의 너비를 맞추다보니 아이콘의 양 옆으로 빈 공간이 나타나 여백의 일관성을 해치는 관계로 다소 보기 안좋은 것 같습니다.

읽어주셔서 감사합니다. 좋은 하루 되세요.

**Comment by HAERUHAERU** [comment]
안녕하세요. 해루입니다. 
문의해주신 내용은 잘 읽어봤습니다. 해당 문제는 기획 단계일 때 항목의 내용과 순서를 이리저리 변경하다가 수정이 누락된 듯 합니다. 덕분에 저도 잊고 있었던 아주 중요한 실수를 알게 됐네요. 특히나 코드가 더러움의 끝판왕임에도 불구하고 클래스명을 찾아서 쉬이 판단할 수 있게끔 문의해주신 점에 이루 말할 수 없는 감동을 받았습니다. 코드 해석하시느라 고생하셨습니다. 정말로(...) 

문의하신 내용은 확실하게 수정했습니다. 또한 덧붙여 건의해주신 내용도 반영했습니다. 근데 2rem으로 했을 때 Job 헤더명 부분이 너무 빡빡하게 느껴져서 2.2rem으로 지정했고, Job 열의 순서를 Name 앞으로 변경했습니다. 이는 해루스킨 때와 같은 배치인데 결국은 다시 돌아가네요. 
배치를 변경한 이유는 아이콘 너비만큼으로 행을 줄이게 되면 다른 행과의 간격이 어긋나보이기에 그렇습니다. 차선으로 아이콘 너비도 사용자가 직접 조정할 수 있게 추가해도 됐으나 굳이 그렇게까지 늘리고 싶어하는 분들은 없을 것 같고;; 위치만 바꿔주면 해결될 것 같아 오랜 시간 고민하고 적용합니다. 
다만 새로운 배치(아이콘 - 이름)의 단점은 랭킹을 표시했을 때 조금 복잡한 느낌을 받을 수 있다는 점(아이콘 1. YOU)인데요. 이는 레이드 모드 테이블 때도 비슷하게 적용되므로 적응하면 괜찮을 듯 합니다. 랭킹은 켜고 끌 수 있으니 크게 문제가 되지 않을 것 같기도 하고요. 

더불어 버그 제보 및 좋은 건의 해주셔서 정말 감사하고 깃허브에 제보해주시니 매우 편하네요. 앞으로도 혹 수정사항이나 건의사항이 있다면 주저말고 두드려 주세요. 정말 감사합니다!

**Comment by HAERUHAERU** [comment]
You should delete the localstorage and cache files. 
Please refer to the link below.

https://docs.google.com/presentation/d/1U7-Vgv6UA2_EFdvw3m8BI-5-9T91WeKTflDuR7rEx-U/edit#slide=id.g2436c33a36_0_2
