### ISSUE TITLE
Overlay never entering standby

### ISSUE THREAD

**Issue by ghost** [HAERUHAERU/mopimopi#14]
I have an issue where the overlay, after combat, never enters standby. I have standby mode enabled and the timer set to three minutes.
I don't know what to provide in terms of logs or files, but ask and you shall receive.

**Comment by 2phite** [comment]
I have the same issue. Happy to provide logs on request.

**Comment by illegaler** [comment]
I have the same problem

**Comment by chernobog** [comment]
Same issue to report. Seems like it will sleep correctly once per session, but then it stops activating the sleep display.

**Comment by illegaler** [comment]
The issue has been fixed https://github.com/HAERUHAERU/mopimopi/commit/df1433923b8b45c9be7c5f2b147a301fb6f43321
Exiting ACT and deleting the cache folder location in ~\AppData\Roaming\Advanced Combat Tracker
The standby mode will now work properly

**Comment by chernobog** [comment]
Confirmed.  Deleting "%userprofile%\AppData\Roaming\Advanced Combat Tracker\OverlayPluginCache\" has restored the standby functionality. Tiny downside, that does reset customizations to the overlay. Not a big deal to set them up again.

**Comment by 2phite** [comment]
Following this change, the overlay now goes into standby while in combat. Tested on ACT version 3.6.0, which was updated after this fix. I deleted the folder `%userprofile%\AppData\Roaming\Advanced Combat Tracker\OverlayPluginCache` before testing, as mentioned above.

**Comment by chernobog** [comment]
~~I can't reproduce that. I've been attacking a Striking Dummy for over five minutes, and the overlay is still active.~~

**Comment by sennematic** [comment]
I also am having the issue where it enters standby during combat.
To reproduce this error:
1) Enter any combat (ie: striking dummy) -- overlay works as normal
2) End combat
3) Enter a new combat -- parser will enter into standby from the timer based on the first combat instance. Overlay will show the correct total Raid DPS/Timer/Current Target but will stay in compact/standby mode where you cannot view individual results

Deleting the cache folder did not fix this issue for me, although it did let me get through 2 combats before the issue occurred

**Comment by ghost** [comment]
Same issue, @sennematic described it perfectly. I'll add that the overlay shows up again if you open its settings menu.

**Comment by chernobog** [comment]
I can confirm, I'm seeing that issue under the circumstances @sennematic describes.

**Comment by illegaler** [comment]
Yea, same issue.

**Comment by cskampas** [comment]
+1.  Regression new as of the 5/14 change as far as I can tell.

There was a pr to add the instructions to clear cache more recently.  I have done this, and the issue persists.  The encounter timer will continue to tick up, but no information is displayed.  Issue is isolated to mopimopi, act and other overlays display correctly

Based on info here, I will try disabling standby mode or putting it at a substantially longer timer than 3 minutes--let me see if that helps, not sure if it will--for now, until a fix is in.

**Comment by HammerBag** [comment]
I won't be able to test but looking at the code in process.js (which was updated to fix the original issue) it looks like it sets OnStopFlag to true arbitrarily if last combat is active. I think that needs to be moved into the else statement to solve the issue. I should be able to test this tonight (approx 11hrs after this post time) but if anyone else wants to take a crack at it, that's what seemed like the place to start when I looked at the code last night (but game was down so couldn't test any changes)

**Comment by illegaler** [comment]
The issue has been fixed, thanks to the quick work of HAERU :)

**Comment by sennematic** [comment]
Confirmed working after update :)

**Comment by ghost** [comment]
Also confirmed working! Closing the issue, thank you for the fix!
