### ISSUE TITLE
FR Translation

### ISSUE THREAD

**Issue by mooondark** [HAERUHAERU/mopimopi#4]
Hi there,
I want to add a French translation for this fantastic skin. Should I just add FR lines in lang.js or it needs more work ?

**Comment by HAERUHAERU** [comment]
Oh thank you!
But I'm not sure if you'll be all right because it has a lot of translate data.
Add the FR line to lang.js and dic.js and send the file to ffxivhaeru@gmail.com.

I will upload after internal testing to local server.

**Comment by HAERUHAERU** [comment]
> Hi there,
> I want to add a French translation for this fantastic skin. Should I just add FR lines in lang.js or it needs more work ?

Oh thank you!
But I'm not sure if you'll be all right because it has a lot of translate data.
Add the FR line to lang.js and dic.js and send the file to ffxivhaeru@gmail.com.

I will upload after internal testing to local server.

**Comment by mooondark** [comment]
Ok let's do it like that. Don't worry, i'm not afraid,i've already translated cacbot and ngld's overlayplugin :)

**Comment by mooondark** [comment]
Mail sent.

**Comment by mooondark** [comment]
Changes merged.
