### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by Feanarus** [HAERUHAERU/mopimopi#5]
Hey,

if i click on the overlay "End Encounter" i recieve the following Info: MopiMopi-Overlay: BrowserConsole: Uncaught ReferenceError: overlayWindowId is not defined (Source: https://haeruhaeru.github.io/mopimopi/js/core.js, Line: 190)

in addition i have two other lines: 
1. MopiMopi-Overlay: BrowserConsole: ChangeZone:[object Object] (Source: https://haeruhaeru.github.io/mopimopi/js/core.js, Line: 343)
2. MopiMopi-Overlay: BrowserConsole: [object Object] (Source: https://haeruhaeru.github.io/mopimopi/js/process.js, Line: 12)

if i was in combat the overlay is still "in fight" so it do not show the history tab or turns back to idle-mode after x minutes

i hope the information is helpful

PS: i use the ngld-overlay WSServer

**Comment by HAERUHAERU** [comment]
> Hey,
> 
> if i click on the overlay "End Enchounter" i recieve the following Info: MopiMopi-Overlay: BrowserConsole: Uncaught ReferenceError: overlayWindowId is not defined (Source: https://haeruhaeru.github.io/mopimopi/js/core.js, Line: 190)
> 
> in addition i have two other lines:
> 
> 1. MopiMopi-Overlay: BrowserConsole: ChangeZone:[object Object] (Source: https://haeruhaeru.github.io/mopimopi/js/core.js, Line: 343)
> 2. MopiMopi-Overlay: BrowserConsole: [object Object] (Source: https://haeruhaeru.github.io/mopimopi/js/process.js, Line: 12)
> 
> if i was in combat the overlay is still "in fight" so it do not show the history tab or turns back to idle-mode after x minutes
> 
> i hope the information is helpful
> 
> PS: i use the ngld-overlay WSServer

I want to test ngld-overlay but it doesn't work on Korea server. ;_;
For now, I temporarily processed it. Please check. I'll patch exactly after Dec 3.

**Comment by Feanarus** [comment]
thanks for your fast response, ok the only Info that remain is the changezone thing the two other dont show up anymore while i click on "End Encounter" 
sadly the history tab (not listed between screenshot and end encounter) or turns back to idle-mode after x minutes still do not work

**Comment by HAERUHAERU** [comment]
Please try again after this time. Thanks!!

**Comment by HAERUHAERU** [comment]
> thanks for your fast response, ok the only Info that remain is the changezone thing the two other dont show up anymore while i click on "End Encounter"
> sadly the history tab (not listed between screenshot and end encounter) or turns back to idle-mode after x minutes still do not work

Please try again after this time. Thanks!!

**Comment by Lalapauwah** [comment]
Hi, sadly the problem is still there.  If you use your overlay with ngld's overlay plugin the history tab and standby modus wont work.
in websocket it works fine, but the overlay plugin is much much nicer to use for all other things.

Edit: In Websocket it does not work either it seems.

i use this url, https://haeruhaeru.github.io/mopimopi/?HOST_PORT=ws://127.0.0.1:10501/

the other one does have missing icons and so on

**Comment by HAERUHAERU** [comment]
> Hi, sadly the problem is still there. If you use your overlay with ngld's overlay plugin the history tab and standby modus wont work.
> in websocket it works fine, but the overlay plugin is much much nicer to use for all other things.
> 
> Edit: In Websocket it does not work either it seems.
> 
> i use this url, https://haeruhaeru.github.io/mopimopi/?HOST_PORT=ws://127.0.0.1:10501/
> 
> the other one does have missing icons and so on

Oh Thank you very much!
This problem is because the variable type has changed.
I FIXED. It works fine now! Please check the overlay :)
