### ISSUE TITLE
Implementing ACTWebSocket

### ISSUE THREAD

**Issue by bsides** [HAERUHAERU/mopimopi#6]
Hi there! 

I don't know if you speak english, I hope you do. I'm contacting you to see if you could help me implementing ACTWebSocket into my overlay: [H O R I Z O V E R L A Y](https://github.com/bsides/horizoverlay)

I got the JavaScripts from https://github.com/ZCube/ACTWebSocket but they aren't helping me much. I'm using React in my build so global stuff like that is a little harder to implement. Regardless, if I use these JavaScript straight into my HTML they also don't seem to work. I could read them through but if you could help me before it would be great.

Thank you in advance!

**Comment by HAERUHAERU** [comment]
Oh, Amazing overlay! 
I think it works pretty well...! What is the problem?
