### ISSUE TITLE
Overlay not displaying properly

### ISSUE THREAD

**Issue by jiseokcube** [HAERUHAERU/mopimopi#6]
Hello, when I tried using the overlay today, it would only display like this
![image](https://user-images.githubusercontent.com/13512335/69375287-02bf7f00-0c76-11ea-8211-eddeff0b7821.png)
ACT parses fine, and the overlay works in Chrome, just not through OverlayProc. I have tried reinstalling from scratch, clearing the cache, and changing the URL.

ACTWebSocket version is 1.3.3.9

**Comment by mooondark** [comment]
I had the same problem. Click on Open DevTools > Application then _Clear Storage_.
Your data will be wiped but it will work again. (Or you can try to clear _Cache Storage_).

**Comment by jiseokcube** [comment]
I only see Open DevTools when using OverlayPlugin (currently using ACTWebSocket instead), and I don't see an Application tab, unless you mean the Application Cache/Cache Storage under Resources.

**Comment by HAERUHAERU** [comment]
I FIXED IT. SORRY FOR THE INCONVENIENC. ;_;

**Comment by HAERUHAERU** [comment]
> Hello, when I tried using the overlay today, it would only display like this
> ![image](https://user-images.githubusercontent.com/13512335/69375287-02bf7f00-0c76-11ea-8211-eddeff0b7821.png)
> ACT parses fine, and the overlay works in Chrome, just not through OverlayProc. I have tried reinstalling from scratch, clearing the cache, and changing the URL.
> 
> ACTWebSocket version is 1.3.3.9

I FIXED IT. SORRY FOR THE INCONVENIENCE. ;_;
Please reload the overlay or restart the ACT.

**Comment by jiseokcube** [comment]
No worries! It works just like normal now, thank you for the quick fix!
